/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ailatrieuphu.Form;

import ailatrieuphu.Dao.XepHangDao;
import ailatrieuphu.Helper.DialogHelper;
import ailatrieuphu.Model.TaiKhoan;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class JFrameXepHang extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormHuongDan
     */
    XepHangDao XepHangDao = new XepHangDao();
    public void fillTop10(){
        int top=0;
        DefaultTableModel model = (DefaultTableModel) tblXepHang.getModel();
        model.setRowCount(0);
        try{
            List<TaiKhoan> list = XepHangDao.select();
            for(TaiKhoan tk:list){
                top++;
                Object[] row = {
                    top,tk.getHoTen(),tk.getDiem()
                };
                model.addRow(row);
            }
        }
        catch(Exception e){
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }
    public void fillTableForName(){
        DefaultTableModel model = (DefaultTableModel) tblXepHang.getModel();
        model.setRowCount(0);
        try{
            String keyword = txtTimKiem.getText();
            List<TaiKhoan> list = XepHangDao.timKiemNguoiChoiTheoTen(keyword);
            for(TaiKhoan tk: list){
                Object[] row ={
                    tk.getHoTen(),
                    tk.getDiem()
                };
                model.addRow(row);
            }
        }
        catch(Exception e){
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }
    public JFrameXepHang() {
        initComponents();
        fillTop10();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        Panel = new javax.swing.JPanel();
        ScrollPane = new javax.swing.JScrollPane();
        tblXepHang = new javax.swing.JTable();
        btnOk = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JFormattedTextField();
        lblXepHang = new javax.swing.JLabel();
        lblTimKiem = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jEditorPane1);

        setClosable(true);

        Panel.setLayout(null);

        tblXepHang.setBackground(java.awt.Color.blue);
        tblXepHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblXepHang.setForeground(new java.awt.Color(255, 255, 255));
        tblXepHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Top", "Họ Tên", "Điểm"
            }
        ));
        tblXepHang.setEnabled(false);
        ScrollPane.setViewportView(tblXepHang);

        Panel.add(ScrollPane);
        ScrollPane.setBounds(30, 120, 710, 290);

        btnOk.setBackground(java.awt.Color.blue);
        btnOk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOk.setForeground(new java.awt.Color(255, 255, 255));
        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        Panel.add(btnOk);
        btnOk.setBounds(330, 440, 100, 40);

        txtTimKiem.setBackground(java.awt.Color.blue);
        txtTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyPressed(evt);
            }
        });
        Panel.add(txtTimKiem);
        txtTimKiem.setBounds(160, 70, 580, 40);

        lblXepHang.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblXepHang.setForeground(new java.awt.Color(255, 255, 255));
        lblXepHang.setText("Xếp Hạng");
        Panel.add(lblXepHang);
        lblXepHang.setBounds(330, 10, 160, 50);

        lblTimKiem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        lblTimKiem.setText("Tìm Kiếm");
        Panel.add(lblTimKiem);
        lblTimKiem.setBounds(40, 70, 110, 30);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ailatrieuphu/Form/Img/123.png"))); // NOI18N
        Panel.add(lblBackground);
        lblBackground.setBounds(-130, 0, 910, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyPressed
        // TODO add your handling code here:
        fillTableForName();
    }//GEN-LAST:event_txtTimKiemKeyPressed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnOkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JButton btnOk;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lblXepHang;
    private javax.swing.JTable tblXepHang;
    private javax.swing.JFormattedTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
