/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ailatrieuphu.Form;

import ailatrieuphu.Dao.LinhVucDao;
import ailatrieuphu.Helper.DialogHelper;
import ailatrieuphu.Helper.ShareHelper;
import ailatrieuphu.Model.LinhVuc;
import ailatrieuphu.Model.TaiKhoan;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.zip.Checksum;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author admin
 */
public class JFrameChinh extends javax.swing.JFrame {

    /**
     * Creates new form FormChinh
     */
    LinhVucDao LinhVucDao=new LinhVucDao();
    public JFrameChinh() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        loadLinhVuc();
        statusLogin();
    }
    public void openDoiThuong(){
        JFrameDoiThuong form = new JFrameDoiThuong();
        DesktopPane.add(form);
        form.setVisible(true);
    }
    public void openXepHang(){
        JFrameXepHang form = new JFrameXepHang();
        DesktopPane.add(form);
        form.setVisible(true);
    }
    public void openChoi() throws SQLException{
        LinhVuc linhVuc= new LinhVuc();
        if (cbLinhVuc.getSelectedItem().toString()=="All") {
            linhVuc=null;
        }else{
        linhVuc=LinhVucDao.findMaLinhVuc(cbLinhVuc.getSelectedItem().toString());
        }
        JFrameChoi form = new JFrameChoi(linhVuc);
        DesktopPane.add(form);
        form.setVisible(true);
    }
    public void openDangNhap(){
        new JFrameDangNhap(this, true).setVisible(true);

    }
    public void openAdmin(){
        JFrameAdmin form = new JFrameAdmin();
        DesktopPane.add(form);
        form.setVisible(true);
    }
    public void openHuongDan(){
        new JFrameHuongDan(this, true).setVisible(true);
    }
    public void loadLinhVuc(){
           DefaultComboBoxModel model = (DefaultComboBoxModel) cbLinhVuc.getModel(); 
           model.removeAllElements();
           model.addElement("All");
           try{
               List<LinhVuc> list = LinhVucDao.select();
               for(LinhVuc lv:list){
                   model.addElement(lv.getTenLinhVuc());
               }
           }
           catch(Exception e){
               DialogHelper.alert(this, "Lỗi truy vấn dữ liệu");
           }
    }

    public void statusLogin(){
        if(ShareHelper.USER!=null){
            if (ShareHelper.USER.getAdmin()) {
                btnAdmin.setVisible(true);
            }else{
                btnAdmin.setVisible(false);
            }
            btnDangNhap.setText("Đăng Xuất");
            lblDiem.setText(ShareHelper.USER.getDiem()+"");
            lblTen.setText(ShareHelper.USER.getHoTen());
        }else{
            btnAdmin.setVisible(false);
            btnDangNhap.setText("Đăng Nhập");
            lblDiem.setText("");
            lblTen.setText("");
        }
    }
    
    public boolean checkLogin(){
        if(ShareHelper.USER!=null){
            return true;
        }
        return false;
    }
    public void setModel(boolean trangthai){
        btnChoi.setEnabled(trangthai);
        btnAdmin.setEnabled(trangthai);
        btnDangNhap.setEnabled(trangthai);
        btnHuongDan.setEnabled(trangthai);
        btnThoat.setEnabled(trangthai);
        btnXepHang.setEnabled(trangthai);
        btnDoiThuong.setEnabled(trangthai);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane = new javax.swing.JDesktopPane();
        lblBackground = new javax.swing.JLabel();
        PanelChucNang = new javax.swing.JPanel();
        btnXepHang = new javax.swing.JButton();
        btnChoi = new javax.swing.JButton();
        btnHuongDan = new javax.swing.JButton();
        btnDoiThuong = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        cbLinhVuc = new javax.swing.JComboBox<>();
        lblXinChao = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        lblDiem = new javax.swing.JLabel();
        btnAdmin = new javax.swing.JButton();
        lblLinhVuc = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DesktopPane.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                DesktopPaneComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                DesktopPaneComponentRemoved(evt);
            }
        });
        DesktopPane.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                DesktopPaneAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        DesktopPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                DesktopPaneComponentShown(evt);
            }
        });

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ailatrieuphu/Form/Img/BachgroundMain.png"))); // NOI18N

        DesktopPane.setLayer(lblBackground, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DesktopPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBackground)
                .addGap(0, 0, 0))
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DesktopPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBackground))
        );

        PanelChucNang.setBackground(new java.awt.Color(55, 4, 77));
        PanelChucNang.setLayout(null);

        btnXepHang.setBackground(java.awt.Color.blue);
        btnXepHang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXepHang.setForeground(new java.awt.Color(255, 255, 255));
        btnXepHang.setText("Xếp Hạng");
        btnXepHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXepHangActionPerformed(evt);
            }
        });
        PanelChucNang.add(btnXepHang);
        btnXepHang.setBounds(14, 492, 148, 37);

        btnChoi.setBackground(java.awt.Color.blue);
        btnChoi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnChoi.setForeground(new java.awt.Color(255, 255, 255));
        btnChoi.setText("Chơi");
        btnChoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoiActionPerformed(evt);
            }
        });
        PanelChucNang.add(btnChoi);
        btnChoi.setBounds(14, 382, 148, 37);

        btnHuongDan.setBackground(java.awt.Color.blue);
        btnHuongDan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHuongDan.setForeground(new java.awt.Color(255, 255, 255));
        btnHuongDan.setText("Hướng Dẫn");
        btnHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuongDanActionPerformed(evt);
            }
        });
        PanelChucNang.add(btnHuongDan);
        btnHuongDan.setBounds(14, 547, 148, 37);

        btnDoiThuong.setBackground(java.awt.Color.blue);
        btnDoiThuong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDoiThuong.setForeground(new java.awt.Color(255, 255, 255));
        btnDoiThuong.setText("Đổi Thưởng");
        btnDoiThuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiThuongActionPerformed(evt);
            }
        });
        PanelChucNang.add(btnDoiThuong);
        btnDoiThuong.setBounds(14, 437, 148, 37);

        btnThoat.setBackground(java.awt.Color.blue);
        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        PanelChucNang.add(btnThoat);
        btnThoat.setBounds(14, 602, 148, 37);

        cbLinhVuc.setBackground(java.awt.Color.blue);
        cbLinhVuc.setEditable(true);
        cbLinhVuc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbLinhVuc.setForeground(new java.awt.Color(255, 255, 255));
        cbLinhVuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbLinhVuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLinhVucActionPerformed(evt);
            }
        });
        PanelChucNang.add(cbLinhVuc);
        cbLinhVuc.setBounds(14, 327, 148, 37);

        lblXinChao.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblXinChao.setForeground(new java.awt.Color(255, 255, 255));
        lblXinChao.setText("Xin Chào");
        PanelChucNang.add(lblXinChao);
        lblXinChao.setBounds(14, 13, 65, 19);

        lblTen.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTen.setForeground(java.awt.Color.red);
        PanelChucNang.add(lblTen);
        lblTen.setBounds(14, 39, 160, 26);

        lblDiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDiem.setForeground(new java.awt.Color(255, 255, 0));
        PanelChucNang.add(lblDiem);
        lblDiem.setBounds(14, 72, 148, 22);

        btnAdmin.setBackground(java.awt.Color.blue);
        btnAdmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnAdmin.setText("Admin");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        PanelChucNang.add(btnAdmin);
        btnAdmin.setBounds(14, 151, 148, 37);

        lblLinhVuc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLinhVuc.setForeground(new java.awt.Color(255, 255, 255));
        lblLinhVuc.setText("Lĩnh Vực");
        PanelChucNang.add(lblLinhVuc);
        lblLinhVuc.setBounds(12, 287, 79, 22);

        btnDangNhap.setBackground(java.awt.Color.blue);
        btnDangNhap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("Đăng Nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        PanelChucNang.add(btnDangNhap);
        btnDangNhap.setBounds(14, 101, 148, 37);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(DesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PanelChucNang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DesktopPane, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbLinhVucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLinhVucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLinhVucActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnDoiThuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiThuongActionPerformed
        if(checkLogin()){
            openDoiThuong();
        }else{
            DialogHelper.alert(DesktopPane, "Bạn cần đăng nhập để sử dụng chức năng");
        }
    }//GEN-LAST:event_btnDoiThuongActionPerformed

    private void btnXepHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXepHangActionPerformed
        // TODO add your handling code here:
        if(checkLogin()){
            openXepHang();
        }else{
            DialogHelper.alert(DesktopPane, "Bạn cần đăng nhập để sử dụng chức năng");
        }
    }//GEN-LAST:event_btnXepHangActionPerformed

    private void btnChoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoiActionPerformed
        try {
            // TODO add your handling code here:
            openChoi();
        } catch (SQLException ex) {
            Logger.getLogger(JFrameChinh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnChoiActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
        openAdmin();
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuongDanActionPerformed
        // TODO add your handling code here:
        openHuongDan();
    }//GEN-LAST:event_btnHuongDanActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        if (ShareHelper.USER!=null) {
            ShareHelper.logout();
        }else{
            openDangNhap();
        }
        statusLogin();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void DesktopPaneComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_DesktopPaneComponentRemoved
        // TODO add your handling code here:
        statusLogin();
    }//GEN-LAST:event_DesktopPaneComponentRemoved

    private void DesktopPaneComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_DesktopPaneComponentAdded
        // TODO add your handling code here:
        statusLogin();
    }//GEN-LAST:event_DesktopPaneComponentAdded

    private void DesktopPaneAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_DesktopPaneAncestorAdded
        statusLogin();
    }//GEN-LAST:event_DesktopPaneAncestorAdded

    private void DesktopPaneComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DesktopPaneComponentShown
        // TODO add your handling code here:
        statusLogin();
    }//GEN-LAST:event_DesktopPaneComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JPanel PanelChucNang;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnChoi;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnDoiThuong;
    private javax.swing.JButton btnHuongDan;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXepHang;
    private javax.swing.JComboBox<String> cbLinhVuc;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblDiem;
    private javax.swing.JLabel lblLinhVuc;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblXinChao;
    // End of variables declaration//GEN-END:variables
}
